 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (585, 'Metal Kharkiv', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (382, 'Fk Sevastopol', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (583, 'Umraniyespor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (579, 'Us Cremonese', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (18, 'England', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (209, 'Newcastle United', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (355, 'Ea Guingamp', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (464, 'Fc Ingolstadt 04', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (506, 'Amiens Sc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (273, 'Real Betis Sevilla', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (103, 'Paraguay', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (258, 'Akhmat Grozny', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (478, 'Ae Larisa', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (256, 'Vfl Wolfsburg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (458, 'Syria', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (548, 'Ingulets Petrove', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (527, 'Nimes Olympique', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (358, 'Tom Tomsk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (219, 'Montserrat', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (206, 'Afc Sunderland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (255, 'Guadeloupe', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (498, 'Pas Lamia 1964', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (166, 'Aberdeen Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (433, 'Sbv Excelsior Rotterdam', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (235, 'Fc Schalke 04', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (92, 'Udinese Calcio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (192, 'Galatasaray Istanbul', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (401, 'Seychelles', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (226, 'Fc Southampton', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (214, 'Bayer 04 Leverkusen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (518, 'Bahrain', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (534, 'Kolos Kovalivka', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (132, 'Aris Thessaloniki', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (546, 'Fk Minaj', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (55, 'Faroe Islands', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (121, 'Finland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (241, 'Comoros', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (145, 'North Macedonia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (287, 'Willem Ii Tilburg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (289, 'Rkc Waalwijk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (386, 'Panetolikos Gfs', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (512, 'Fc Emmen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (68, 'Istanbul Basaksehir Fk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (140, 'Ao Platanias', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (528, 'Enisey Krasnoyarsk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (450, 'Eritrea', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (108, 'Kardemir Karabukspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (507, 'Neukaledonien', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (318, 'Libya', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (488, 'Kas Eupen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (97, 'Delfino Pescara 1936', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (213, '1 Fc Nurnberg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (381, 'Crystal Palace', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (416, 'Hamilton Academical Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (291, 'Vvv Venlo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (84, 'Liechtenstein', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (38, 'Bulgaria', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (455, 'Jordan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (262, 'Kuban Krasnodar', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (212, 'Vfb Stuttgart', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (19, 'Fc Reading', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (476, 'Zirka Kropyvnytskyi', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (111, 'Ofi Kreta', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (302, 'Fc Groningen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (271, 'United Arab Emirates', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (403, 'Kenya', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (432, 'St. Kitts & Nevis', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (146, 'Kryvbas Kryvyi Rig', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (511, 'Portimonense Sc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (572, 'Cuba', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (243, 'Hannover 96', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (268, 'Ca Osasuna', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (238, 'Dinamo Moskau', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (190, 'Israel', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (519, 'San Marino', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (307, 'Fc Granada', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (239, 'Tajikistan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (378, 'Apollon Smyrnis', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (451, 'Sv Darmstadt 98', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (333, 'Rsc Anderlecht', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (376, 'Cyprus', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (250, 'Montpellier Hsc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (290, 'Heracles Almelo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (330, 'Standard Luttich', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (370, 'Malaysia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (33, 'Volyn Lutsk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (491, 'Deportivo Alaves', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (575, 'Royale Union Saint Gilloise', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (524, 'Fortuna Sittard', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (91, 'Armenia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (521, 'Mke Ankaragucu', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (122, 'Inter Mailand', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (29, 'Brazil', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (377, 'Gs Ergotelis', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (183, 'Karpaty Lviv', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (560, 'Fk Khimki', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (522, 'Desna Chernigiv', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (309, 'Ecuador', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (495, 'Nk Veres Rivne', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (513, 'Sd Huesca', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (567, 'Us Salernitana 1919', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (72, 'Antalyaspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (242, 'Fc Bayern Munchen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (109, 'Bursaspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (587, 'Casa Pia Ac', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (187, 'West Bromwich Albion', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (77, 'Italy', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (438, 'Fc Dordrecht', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (93, 'Ac Mailand', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (114, 'Haiti', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (354, 'Afghanistan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (564, 'Ionikos Nikeas', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (12, 'Scotland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (264, 'Ud Levante', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (244, 'Spartak Moskau', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (362, 'As Livorno', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (245, 'Zska Moskau', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (48, 'Cote dIvoire', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (184, 'Ross County Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (529, 'Kyrgyzstan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (52, 'Korea', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (5, 'Moreirense Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (113, 'Veria Nps', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (342, 'Togo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (88, 'Sk Tavriya Simferopol', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (364, 'Uzbekistan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (420, 'Sd Eibar', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (483, 'Fc Middlesbrough', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (312, 'Rio Ave Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (515, 'Livingston Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (557, 'Beerschot V A ', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (200, 'Fc Everton', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (280, 'Fc Getafe', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (551, 'Fatih Karagumruk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (308, 'Fc Pacos De Ferreira', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (422, 'Niki Volou', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (578, 'Fakel Voronezh', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (306, 'Espanyol Barcelona', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (293, 'Benin', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (440, 'Sm Caen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (346, 'Kaa Gent', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (477, 'Alanyaspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (56, 'Portugal', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (20, 'Grenada', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (98, 'Genua Cfc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (44, 'Latvia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (191, 'Fc Fulham', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (65, 'Morocco', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (300, 'Guatemala', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (434, 'Rc Lens', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (138, 'Apo Levadiakos', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (541, '1 Fc Union Berlin', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (70, 'Goverla Uzhgorod', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (299, 'Sc Heerenveen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (475, 'Fc Crotone', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (228, 'Aston Villa', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (536, 'Denizlispor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (60, 'Kv Kortrijk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (298, 'Gd Estoril Praia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (549, 'Tanzania', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (189, 'Stoke City', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (51, 'Ghana', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (31, 'Northern Ireland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (366, 'India', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (101, 'Canada', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (286, 'Nec Nijmegen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (323, 'Fc Porto', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (373, 'Central African Republic', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (141, 'Metalist Kharkiv', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (46, 'Germany', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (555, 'Fc Cadiz', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (301, 'Az Alkmaar', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (360, 'Fc Vestsjaelland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (4, 'Guinea', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (30, 'United States', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (514, 'Somalia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (64, 'Stade Reims', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (281, 'Fc Valenciennes', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (426, 'Sao Tome and Principe', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (532, 'Pfk Tambov', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (322, 'Krc Genk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (154, 'Equatorial Guinea', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (582, 'Istanbulspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (327, 'Costa Rica', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (542, 'Vietnam', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (415, 'Leicester City', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (266, 'Olympique Marseille', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (452, 'Iraklis Thessaloniki', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (89, 'Inverness Caledonian Thistle Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (25, 'Nigeria', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (185, 'Aarhus Gf', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (397, 'Losc Lille', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (34, 'Switzerland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (537, 'Gaziantep Fk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (554, 'Leeds United', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (27, 'Spain', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (304, 'Feyenoord Rotterdam', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (332, 'Palestine', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (439, '1 Fc Koln', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (456, 'Frosinone Calcio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (172, 'Estonia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (471, 'Cd Tondela', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (127, 'Panthrakikos Komotini', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (199, 'Queens Park Rangers', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (169, 'Ac Horsens', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (177, 'Hibernian Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (374, 'Mozambique', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (234, 'El Salvador', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (159, 'Sonderjyske', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (171, 'Dundee United Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (531, 'Belenenses Sad', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (517, 'Vejle Boldklub', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (86, 'Elazigspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (249, 'As Nancy Lorraine', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (130, 'Panathinaikos Athen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (282, 'Celta Vigo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (215, 'Fc Arsenal', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (297, 'Fc Lorient', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (175, 'Fc Nordsjaelland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (418, 'Fc Burnley', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (232, 'Mordovia Saransk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (317, 'Sc Braga', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (453, 'Carpi Fc 1909', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (99, 'As Rom', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (553, 'Mauritius', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (459, 'Ankaraspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (497, 'Desportivo Aves', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (324, 'Lierse Sk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (229, 'Amkar Perm', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (119, 'Besiktas Istanbul', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (429, 'Olimpik Donetsk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (66, 'Vitoria Setubal Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (112, 'Palermo Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (568, 'Giresunspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (449, 'Ud Las Palmas', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (530, 'Cd Santa Clara', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (123, 'Eskisehirspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (446, 'Gfc Ajaccio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (410, 'Ural Ekaterinburg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (447, 'Afc Bournemouth', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (406, 'Fc Arouca', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (454, 'Malta', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (314, 'Cape Verde', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (151, 'Metalurg Donetsk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (272, 'Real Sociedad San Sebastian', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (21, 'Ireland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (492, 'Gd Chaves', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (59, 'France', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (194, 'Lithuania', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (339, 'Cd Nacional', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (79, 'Fc Turin', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (195, 'Swansea City', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (277, 'Fc Malaga', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (310, 'Vitoria Guimaraes Sc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (163, 'Brondby If', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (516, 'Vendsyssel Ff', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (352, 'Go Ahead Eagles Deventer', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (11, 'Dundee Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (39, 'Metalurg Zaporizhya Bis 2016 ', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (9, 'Kv Mechelen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (480, 'Nicaragua', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (223, 'Borussia Dortmund', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (581, 'Ac Monza', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (160, 'Norway', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (556, 'Macao', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (220, 'Mexico', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (230, 'Manchester United', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (371, 'Uganda', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (436, 'Suriname', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (165, 'Fc Midtjylland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (493, 'Ska Khabarovsk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (545, 'Arminia Bielefeld', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (504, 'Papua New Guinea', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (481, 'Glasgow Rangers', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (17, 'Wales', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (96, 'Juventus Turin', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (105, 'Ssc Neapel', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (156, 'Kasimpasa', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (205, 'Kazakhstan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (563, 'Vfl Bochum', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (155, 'Olympiakos Piraus', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (274, 'Deportivo La Coruna', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (350, 'Viborg Ff', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (356, 'Eintracht Braunschweig', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (343, 'Sc Beira Mar', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (152, 'Mali', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (523, 'Pfk Lviv', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (379, 'Panama', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (400, 'Hamburger Sv', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (419, 'Hobro Ik', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (547, 'Rukh Lviv', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (265, 'Real Saragossa', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (85, 'Zorya Lugansk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (577, 'Fk Nizhny Novgorod', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (525, 'Laos', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (267, 'Fc Stade Rennes', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (82, 'Argentina', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (351, 'Hull City', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (36, 'Bosnia-Herzegovina', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (395, 'Zambia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (340, 'Congo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (316, 'Cs Maritimo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (347, 'Guinea-Bissau', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (115, 'Gaziantepspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (535, 'Brescia Calcio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (369, 'Hellas Verona', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (90, 'Georgia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (164, 'Odense Boldklub', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (461, 'Pfk Stal Kamyanske', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (336, 'Vitesse Arnheim', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (409, 'Fc Elche', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (217, 'Borussia Monchengladbach', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (393, 'Madagascar', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (467, 'Aruba', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (259, 'Zenit St Petersburg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (558, 'Rotor Volgograd', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (15, 'Norwich City', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (143, 'Chornomorets Odessa', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (359, 'Konyaspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (100, 'Sweden', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (580, 'Fc Volendam', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (402, 'Hertha Bsc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (457, 'Malawi', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (574, 'Andorra', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (74, 'Poland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (485, 'Sparta Rotterdam', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (43, 'Tunisia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (479, 'Lyngby Bk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (275, 'Athletic Bilbao', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (368, 'Kayseri Erciyesspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (435, 'Fc Metz', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (125, 'Sampdoria Genua', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (520, 'Buyuksehir Belediye Erzurumspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (303, 'Ado Den Haag', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (380, 'Lebanon', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (53, 'Azerbaijan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (305, 'Fc Utrecht', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (28, 'Czech Republic', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (225, 'Spartak Vladikavkaz', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (437, 'Mauritania', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (486, 'Dijon Fco', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (276, 'As Saint Etienne', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (463, 'Sco Angers', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (211, 'Sv Werder Bremen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (32, 'Australia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (501, 'Fc Helsingor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (116, 'Fenerbahce Istanbul', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (544, 'Fk Sochi', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (61, 'Cameroon', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (176, 'Celtic Glasgow', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (180, 'Motherwell Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (71, 'Mersin Idmanyurdu', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (361, 'Us Sassuolo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (218, 'Fc Chelsea', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (24, 'Iceland', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (197, 'Oman', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (372, 'Ael Kalloni', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (399, 'Gabon', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (391, 'Luxembourg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (167, 'Esbjerg Fb', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (315, 'Fc Valencia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (69, 'Orduspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (221, 'Algeria', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (147, 'Slovenia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (421, 'Balikesirspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (496, 'Huddersfield Town', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (26, 'Antigua and Barbuda', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (10, 'Colombia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (425, 'Fc Empoli', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (63, 'Real Valladolid', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (411, 'Sporting Lissabon', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (150, 'Arsenal Kiew', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (158, 'Randers Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (288, 'Nac Breda', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (348, 'Ud Almeria', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (430, 'Real Madrid', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (216, 'Fc Kopenhagen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (251, 'Ogc Nizza', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (233, 'Moldova', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (182, 'Kilmarnock Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (334, 'Fc Brugge', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (208, 'Fc Liverpool', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (296, 'Atletico Madrid', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (390, 'Shakhtar Donetsk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (110, 'Chievo Verona', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (423, 'Kvc Westerlo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (179, 'Honduras', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (254, 'Stade Brest 29', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (149, 'Dynamo Kiew', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (204, 'Fc Augsburg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (337, 'Burundi', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (510, 'Fk Tosno', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (188, 'French Guiana', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (157, 'Asteras Tripolis', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (445, 'De Graafschap Doetinchem', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (201, 'Manchester City', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (550, 'Spezia Calcio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (210, 'Eintracht Frankfurt', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (313, 'Academica Coimbra', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (363, 'St. Lucia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (224, 'Volga Nizhniy Novgorod', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (40, 'Russia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (136, 'Lazio Rom', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (326, 'Rsc Charleroi', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (161, 'Netherlands', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (499, 'Yeni Malatyaspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (384, 'China', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (260, 'Martinique', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (134, 'Pas Giannina', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (284, 'Roda Jc Kerkrade', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (263, 'Fc Paris Saint Germain', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (473, 'Cd Feirense', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (78, 'Akhisarspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (37, 'Romania', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (573, 'Metalist 1925 Kharkiv', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (526, 'Wolverhampton Wanderers', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (474, 'Adanaspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (353, 'Philippines', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (186, 'West Ham United', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (240, 'Sc Bastia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (198, 'Aek Athen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (270, 'Olympique Lyon', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (375, 'Zimbabwe', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (431, 'Fc Penafiel', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (76, 'Fc Bologna', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (41, 'Montenegro', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (236, 'Ac Ajaccio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (441, 'Sc Paderborn 07', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (428, 'Fc Cordoba', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (472, 'Indonesia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (509, 'Brighton Amp Hove Albion', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (126, 'Panionios Athen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (443, 'Torpedo Moskau', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (448, 'Fk Oleksandriya', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (47, 'Angola', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (95, 'Atalanta Bergamo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (562, 'Rfc Seraing', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (248, 'Fk Krasnodar', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (181, 'St Johnstone Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (252, 'Krylya Sovetov Samara', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (571, 'Fc Brentford', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (278, 'Fc Toulouse', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (392, 'Cardiff City', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (561, 'Brunei Darussalam', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (148, 'Catania Calcio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (14, 'Greece', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (261, 'Thonon Evian Grand Geneve Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (357, 'Iran', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (203, 'Spvgg Greuther Furth', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (444, 'Cf Uniao Madeira', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (178, 'Guyana', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (584, 'Nottingham Forest', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (417, 'Iraq', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (500, 'Benevento Calcio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (117, 'Chile', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (269, 'Fc Sochaux Montbeliard', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (387, 'Saint-Martin', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (168, 'The Gambia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (329, 'Sc Olhanense', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (35, 'Ukraine', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (328, 'Cercle Brugge', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (8, 'Turkey', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (2, 'Belgium', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (345, 'Benfica Lissabon', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (540, 'Sk Dnipro 1', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (319, 'South Africa', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (388, 'Trinidad and Tobago', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (405, 'Fc Villarreal', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (367, 'Caykur Rizespor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (466, 'Bermuda', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (552, 'Hatayspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (246, 'Anzhi Makhachkala', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (570, 'Adana Demirspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (22, 'Jamaica', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (107, 'Peru', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (442, 'Turkmenistan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (283, 'Pec Zwolle', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (508, 'Royal Antwerpen Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (365, 'Chad', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (408, 'Kv Oostende', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (7, 'Fortuna Dusseldorf', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (73, 'Sivasspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (465, 'Fc Watford', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (396, 'Thailand', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (490, 'Cd Leganes', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (503, 'Spal', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (414, 'Boavista Porto Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (427, 'Royal Excel Mouscron', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (424, 'Cesena Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (487, 'Chinese Taipei', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (257, 'Fc Girondins Bordeaux', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (142, 'Vorskla Poltava', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (227, 'Fk Rostov', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (482, 'Rasenballsport Leipzig', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (45, 'Croatia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (6, 'Uruguay', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (285, 'Rayo Vallecano', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (533, 'Sheffield United', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (193, 'Heart Of Midlothian Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (407, 'Fc Barcelona', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (586, 'Aj Auxerre', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (170, 'St Mirren Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (153, 'Venezuela', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (202, 'Liberia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (137, 'Burkina Faso', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (412, 'Fk Ufa', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (295, 'Psv Eindhoven', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (321, 'Waasland Beveren', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (139, 'Trabzonspor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (385, 'Partick Thistle Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (462, 'Sporting Gijon', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (331, 'Fc Twente Enschede', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (3, 'Es Troyes Ac', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (129, 'Paok Thessaloniki', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (576, 'Fc Vizela', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (538, 'Volos Nps', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (565, 'Clermont Foot 63', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (1, 'Ksc Lokeren', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (106, 'Parma Calcio 1913', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (543, 'Fc Famalicao', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (231, 'Sc Freiburg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (253, 'Tsg 1899 Hoffenheim', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (118, 'Genclerbirligi Ankara', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (94, 'Austria', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (566, 'Venezia Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (489, 'Monaco', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (469, 'Vv St Truiden', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (128, 'Tahiti', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (144, 'Ao Xanthi', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (54, 'Silkeborg If', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (222, '1 Fsv Mainz 05', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (294, 'Gil Vicente Fc', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (135, 'Atromitos Athen', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (207, 'Tottenham Hotspur', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (237, 'Rubin Kazan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (62, 'Hungary', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (133, 'Réunion', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (50, 'Japan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (502, 'Goztepe', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (42, 'Belarus', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (292, 'Curacao', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (398, 'As Monaco', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (196, 'Wigan Athletic', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (81, 'Albania', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (131, 'New Zealand', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (104, 'Cagliari Calcio', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (67, 'Senegal', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (57, 'DR Congo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (174, 'Fk Mariupol', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (279, 'Fc Sevilla', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (569, 'Altay Sk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (58, 'Sv Zulte Waregem', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (325, 'Ethiopia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (539, 'Us Lecce', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (413, 'Arsenal Tula', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (87, 'Egypt', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (16, 'Sierra Leone', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (383, 'Bolivia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (162, 'Aalborg Bk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (320, 'Saudi Arabia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (173, 'Pakistan', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (124, 'Kosovo', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (335, 'Qatar', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (75, 'Slovakia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (83, 'Serbia', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (394, 'Fc Nantes', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (559, 'Sc Farense', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (505, 'Fc Girona', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (102, 'Kayserispor', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (460, 'Niger', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (341, 'Beerschot Ac', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (470, 'Rwanda', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (494, 'Rc Strassburg Alsace', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (344, 'Oud Heverlee Leuven', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (389, 'Dnipro Dnipropetrovsk', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (484, 'Fk Orenburg', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (338, 'Raec Mons', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (468, 'Ajax Amsterdam', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (80, 'Acn Siena 1904', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (23, 'Barbados', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (247, 'Lokomotiv Moskau', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (349, 'Sc Cambuur Leeuwarden', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (49, 'Denmark', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (404, 'Dominican Republic', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (120, 'Ac Florenz', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (311, 'Rcd Mallorca', ''); 
 INSERT INTO `stat-spot-db`.`Country` (`countryId`, `name`, `continent`) VALUES (13, 'Aok Kerkyra', ''); 
