 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (42, 'Modern Pentathlon', 'Modern Pentathlon is a competitive sport.', 4, 16); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (12, 'Artistic Swimming', 'Artistic Swimming is a competitive sport.', 16, 16); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (24, 'Beach Volleyball', 'Beach Volleyball is a competitive sport.', 20, 18); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (18, 'Fencing', 'Fencing is a competitive sport.', 12, 28); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (14, 'Shooting', 'Shooting is a competitive sport.', 9, 27); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (19, 'Badminton', 'Badminton is a competitive sport.', 23, 24); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (15, 'Table Tennis', 'Table Tennis is a competitive sport.', 17, 18); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (4, 'Basketball', 'Basketball is a competitive sport.', 24, 25); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (8, 'Wrestling', 'Wrestling is a competitive sport.', 9, 16); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (7, 'Karate', 'Karate is a competitive sport.', 5, 28); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (11, 'Athletics', 'Athletics is a competitive sport.', 9, 21); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (34, 'Cycling BMX Racing', 'Cycling BMX Racing is a competitive sport.', 10, 30); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (25, 'Sailing', 'Sailing is a competitive sport.', 20, 23); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (33, 'Canoe Sprint', 'Canoe Sprint is a competitive sport.', 8, 16); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (13, 'Judo', 'Judo is a competitive sport.', 7, 26); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (22, 'Archery', 'Archery is a competitive sport.', 22, 27); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (27, 'Trampoline Gymnastics', 'Trampoline Gymnastics is a competitive sport.', 16, 18); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (23, 'Diving', 'Diving is a competitive sport.', 16, 30); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (31, 'Water Polo', 'Water Polo is a competitive sport.', 16, 19); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (43, 'Cycling Mountain Bike', 'Cycling Mountain Bike is a competitive sport.', 6, 16); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (6, 'Swimming', 'Swimming is a competitive sport.', 16, 27); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (30, 'Canoe Slalom', 'Canoe Slalom is a competitive sport.', 24, 19); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (10, 'Baseball/Softball', 'Baseball/Softball is a competitive sport.', 19, 28); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (39, 'Cycling Track', 'Cycling Track is a competitive sport.', 11, 19); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (45, 'Cycling BMX Freestyle', 'Cycling BMX Freestyle is a competitive sport.', 13, 20); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (46, 'Sport Climbing', 'Sport Climbing is a competitive sport.', 7, 26); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (38, 'Tennis', 'Tennis is a competitive sport.', 8, 20); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (35, 'Rugby Sevens', 'Rugby Sevens is a competitive sport.', 8, 16); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (20, 'Boxing', 'Boxing is a competitive sport.', 12, 15); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (29, 'Triathlon', 'Triathlon is a competitive sport.', 4, 30); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (40, 'Golf', 'Golf is a competitive sport.', 22, 20); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (26, 'Hockey', 'Hockey is a competitive sport.', 6, 18); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (36, 'Volleyball', 'Volleyball is a competitive sport.', 5, 20); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (3, 'Rowing', 'Rowing is a competitive sport.', 9, 27); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (44, '3x3 Basketball', '3x3 Basketball is a competitive sport.', 14, 16); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (16, 'Football', 'Football is a competitive sport.', 6, 22); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (32, 'Surfing', 'Surfing is a competitive sport.', 4, 16); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (1, 'Cycling Road', 'Cycling Road is a competitive sport.', 10, 20); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (21, 'Weightlifting', 'Weightlifting is a competitive sport.', 7, 21); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (28, 'Marathon Swimming', 'Marathon Swimming is a competitive sport.', 5, 20); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (37, 'Equestrian', 'Equestrian is a competitive sport.', 19, 23); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (41, 'Skateboarding', 'Skateboarding is a competitive sport.', 16, 27); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (2, 'Artistic Gymnastics', 'Artistic Gymnastics is a competitive sport.', 15, 28); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (5, 'Handball', 'Handball is a competitive sport.', 21, 22); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (9, 'Rhythmic Gymnastics', 'Rhythmic Gymnastics is a competitive sport.', 24, 17); 
 INSERT INTO `stat-spot-db`.`Sport` (`sportId`, `name`, `description`, `playerCount`, `duration`) VALUES (17, 'Taekwondo', 'Taekwondo is a competitive sport.', 17, 15); 
