INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (1, 'Bundesliga', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (2, 'Dfb Pokal', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (3, 'Dfl Supercup', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (4, 'Eredivisie', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (5, 'Toto Knvb Beker', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (6, 'Johan Cruijff Schaal', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (7, 'Jupiler Pro League', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (8, 'Belgian Supercup', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (9, 'Laliga', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (10, 'Copa Del Rey', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (11, 'Supercopa', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (12, 'Liga Portugal Bwin', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (13, 'Allianz Cup', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (14, 'Supertaca Candido De Oliveira', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (15, 'Ligue 1', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (16, 'Trophee Des Champions', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (17, 'Premier League', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (18, 'Efl Cup', 'other', 'league_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (19, 'Fa Cup', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (20, 'Community Shield', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (21, 'Premier Liga', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (22, 'Russian Cup', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (23, 'Russian Super Cup', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (24, 'Premier Liga', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (25, 'Ukrainian Cup', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (26, 'Ukrainian Super Cup', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (27, 'Scottish Premiership', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (28, 'Sfa Cup', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (29, 'Serie A', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (30, 'Italy Cup', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (31, 'Supercoppa Italiana', 'other', 'domestic_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (32, 'Super League 1', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (33, 'Kypello Elladas', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (34, 'Super Lig', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (35, 'Superligaen', 'domestic_league', 'first_tier'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (36, 'Sydbank Pokalen', 'domestic_cup', 'domestic_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (37, 'Uefa Super Cup', 'other', 'uefa_super_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (38, 'Uefa Champions League', 'international_cup', 'uefa_champions_league'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (39, 'Europa League', 'international_cup', 'europa_league'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (40, 'Fifa Klub Wm', 'other', 'fifa_club_world_cup'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (41, 'Uefa Europa Conference League Qualifikation', 'international_cup', 'uefa_europa_conference_league_qualifiers'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (42, 'Uefa Champions League Qualifikation', 'international_cup', 'uefa_champions_league_qualifying'); 
INSERT INTO `stat-spot-db`.`League` (`leagueId`, `type`, `subType`, `name`) VALUES (43, 'Europa League Qualifikation', 'international_cup', 'europa_league_qualifying'); 
