 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (1, 'ABDELMAGID Wael', 87, '1972-04-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (2, 'ABE Junya', 50, '1969-02-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (3, 'ABE Katsuhiko', 50, '1977-09-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (4, 'ADAMA Cherif', null, '1973-08-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (5, 'AGEBA Yuya', 50, '1969-10-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (6, 'AIKMAN Siegfried Gottlieb', 50, '1963-05-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (7, 'AL SAADI Kais', 46, '1964-07-28', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (8, 'ALAMEDA Lonni', 101, '1979-11-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (9, 'ALEKNO Vladimir', null, '1960-01-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (10, 'ALEKSEEV Alexey', null, '1973-11-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (11, 'ALLER CARBALLO Manuel Angel', 27, '1967-11-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (12, 'ALSHEHRI Saad', 320, '1978-01-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (13, 'ALY Kamal', 87, '1979-10-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (14, 'AMAYA GAITAN Fabian', null, '1975-05-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (15, 'AMO AGUADO Pablo', 27, '1975-09-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (16, 'ANDONOVSKI Vlatko', null, '1976-10-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (17, 'ANNAN Alyson', 161, '1974-06-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (18, 'ARNAU CREUS Xavier', 50, '1967-03-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (19, 'ARNOLD Graham', 32, '1966-06-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (20, 'AXNER Tomas', 100, '1973-10-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (21, 'BABER Gareth Colin', null, '1979-11-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (22, 'BACIU Horatiu', 37, '1964-05-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (23, 'BANBULA Wojciech', 74, '1967-06-01', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (24, 'BAO Zhuang', null, '1962-11-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (25, 'BARYLA Pawel', null, '1969-08-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (26, 'BASILIO Mel', 101, '1973-10-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (27, 'BASSO Paola', null, '1978-09-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (28, 'BATCH Colin', 32, '1968-12-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (29, 'BATISTA Fernando', 82, '1979-04-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (30, 'BATISTA SANTIAGO Gerardo', null, '1967-01-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (31, 'BENCIC Filip', 83, '1963-02-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (32, 'BERG Laura', null, '1980-08-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (33, 'BERGE Christian', 160, '1967-01-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (34, 'BILLAVA SURESH Ankitha', 366, '1970-11-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (35, 'BIRO Attila', 62, '1978-10-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (36, 'BLECHER SIDOROVA Svetlana', 190, '1966-09-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (37, 'BLENGINI Gianlorenzo', 77, '1965-12-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (38, 'BOLTON Alice', 25, '1976-06-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (39, 'BREIVIK Marit', 160, '1968-03-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (40, 'BRODERICK William', 29, '1974-09-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (41, 'BRONDELLO Sandy', 32, '1967-02-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (42, 'BROWN Chris', null, '1962-01-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (43, 'BROWN Michael', 25, '1965-01-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (44, 'BRUN Aristide', 94, '1963-05-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (45, 'BUNTING Allan', 131, '1974-12-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (46, 'BURLANDO Giovanna', 77, '1979-10-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (47, 'BUSATO Sergio', null, '1972-03-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (48, 'BUSENKELL Axel', 46, '1969-10-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (49, 'BYRNE Mick', 101, '1969-02-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (50, 'CADENAS MONTANES Manuel', 82, '1966-08-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (51, 'CALDAS Max', 161, '1964-07-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (52, 'CAMPAGNA Alessandro', 77, '1971-06-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (53, 'CARO Carlos', 220, '1976-10-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (54, 'CASAREZ Mary Lucy', 50, '1970-04-19', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (55, 'CASTRO Alex', 117, '1969-04-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (56, 'CHAMBERS Cheryl', 32, '1968-07-19', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (57, 'CHEPAK Anastasiya', 87, '1967-04-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (58, 'CHEPAK Anastasiya', 87, '1962-10-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (59, 'CHERNETSKA Natalia', 14, '1965-10-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (60, 'CHERNETSKA Natalia', 14, '1967-11-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (61, 'CHIARI Simona', 519, '1971-12-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (62, 'CHOI Il Eon', null, '1963-09-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (63, 'CHUN Jooweon', null, '1965-08-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (64, 'CLARK STEPHEN Gregg', 366, '1979-06-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (65, 'COLLET Vincent', 59, '1963-09-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (66, 'COMMENS Adam', 2, '1966-07-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (67, 'COURTEIX David', 59, '1977-02-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (68, 'CRESPI JAUME Margalida', 10, '1964-02-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (69, 'CRUZ Filipe', 47, '1961-08-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (70, 'DAL ZOTTO Renan', 29, '1976-08-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (71, 'DANCER Sean', 21, '1972-08-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (72, 'DANCHENKO Tatiana', null, '1975-06-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (73, 'DAVY Jeremy', 32, '1960-04-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (74, 'DAZA Fabian', 117, '1979-07-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (75, 'de la FUENTE CASTILLO Luis', 27, '1963-10-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (76, 'de MOURA Luizomar', 403, '1975-05-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (77, 'de OLIVEIRA Marcus Ricardo', 29, '1979-11-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (78, 'de VOS Robbert-Jan', 161, '1974-04-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (79, 'DELANEY Mike', 131, '1960-10-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (80, 'DEMCHENKO Zhanna', 205, '1962-11-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (81, 'DIAZ FERNANDEZ Jenaro Manuel', 27, '1971-02-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (82, 'DIAZ HENRIQUEZ Nestor', 404, '1968-03-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (83, 'DIDENKO Natalia', 27, '1973-08-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (84, 'DOBSON Howard', null, '1964-06-19', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (85, 'DORE Karine', 101, '1969-05-19', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (86, 'DROBNJAK Dragisa', 147, '1966-11-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (87, 'DUENAS de GALARZA Jorge', 29, '1972-04-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (88, 'DURO Fernando', 153, '1979-06-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (89, 'DYKSTRA Trisha', 32, '1978-07-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (90, 'ECHEZURIA Manuel', 153, '1978-03-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (91, 'EDDY Anthony', 21, '1973-11-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (92, 'EITOKU Atsushi', 50, '1965-07-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (93, 'ELAFANDI Nour', 87, '1979-06-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (94, 'ELAFANDI Nour', 87, '1975-04-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (95, 'ELEK Gabor', 62, '1963-04-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (96, 'ENGELLAND Chip', null, '1964-11-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (97, 'ENQUIST Susan', null, '1965-03-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (98, 'ERIKSEN Ken', null, '1975-02-01', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (99, 'EWING Gareth', 319, '1974-05-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (100, 'FABRE Julie', 59, '1979-07-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (101, 'FAHMY LATIF Yasmine', 87, '1969-06-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (102, 'FALERO Miguel', 179, '1965-11-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (103, 'FARINELLI Roberta', 77, '1977-09-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (104, 'FARINELLI Roberta', 77, '1967-11-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (105, 'FATOVIC Elvis', 32, '1979-11-19', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (106, 'FAVAREL Pablo', 153, '1968-07-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (107, 'FEDIUSHYNA Tetiana', 35, '1966-09-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (108, 'FERRARO Hernan', 82, '1975-09-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (109, 'FISH Nathan', 190, '1968-01-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (110, 'FLOWERS Tairia', null, '1975-03-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (111, 'FOIREST Laurent', 59, '1961-02-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (112, 'FORREST Scott', null, '1974-02-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (113, 'FRIDAY Mike', null, '1968-11-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (114, 'FUENTES Andrea', null, '1975-10-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (115, 'FUERBRINGER Matthew', null, '1973-07-01', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (116, 'FUJIKI Mayuko', 27, '1979-12-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (117, 'FUJIKI Mayuko', 27, '1969-05-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (118, 'FULI Saiasi', null, '1976-08-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (119, 'GADEMAN Pasha', 101, '1961-04-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (120, 'GAIDUKOV Aleksandr', null, '1967-04-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (121, 'GARCIA HERRERA Manuel', 404, '1966-05-01', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (122, 'GARCIA Nestor', 404, '1969-11-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (123, 'GARCIA PIZARRO Paula', 10, '1967-09-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (124, 'GARNIER Valerie', 59, '1966-05-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (125, 'GERHARDSSON Peter', 100, '1970-08-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (126, 'GIACOBBE Antonio', 43, '1965-03-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (127, 'GIALLOMBARDO Patrizia', 77, '1962-05-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (128, 'GIALLOMBARDO Patrizia', 77, '1978-06-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (129, 'GILLE Guillaume', 59, '1980-04-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (130, 'GINZBURG Ronen', 28, '1977-02-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (131, 'GISLASON Alfred', 46, '1969-09-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (132, 'GOJKOVIC Vladimir', 41, '1963-03-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (133, 'GOMEZ CORA Santiago', 82, '1971-08-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (134, 'GONZALEZ Anibal', 220, '1963-09-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (135, 'GONZALEZ JARENO Angel', 27, '1965-08-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (136, 'GOORJIAN Brian', 32, '1979-04-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (137, 'GORDO MANSILLA Juan David', 27, '1960-11-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (138, 'GRAINGER Adam', 21, '1965-07-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (139, 'GRAUPERA Cristina', 14, '1969-03-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (140, 'GRAZIOSI Gianluca', 77, '1978-02-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (141, 'GRESKOWIAK Arne', 46, '1972-12-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (142, 'GRYZUNOVA Elena', null, '1978-03-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (143, 'GUERRERO LOPEZ Julen', 27, '1968-03-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (144, 'GUERRERO Rolando', 220, '1979-06-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (145, 'GUERRERO Rolando', 220, '1979-05-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (146, 'GUIDETTI Giovanni', 8, '1972-02-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (147, 'GUILLEN Ronald', 153, '1962-06-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (148, 'GUIMARAES Jose Roberto', 29, '1965-10-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (149, 'GUSTAVSSON Tony', 32, '1963-08-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (150, 'HAGER Mark', null, '1963-03-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (151, 'HAIDARA Soualiho', null, '1974-09-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (152, 'HALD Simon', 49, '1976-10-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (153, 'HALKETT Rhett', 161, '1964-02-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (154, 'HAM Darvin de', 25, '1976-11-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (155, 'HARDY William', null, '1980-08-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (156, 'HARROW Laing', 32, '1973-02-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (157, 'HARVEY Laura', null, '1975-06-28', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (158, 'HAVENGA Arno', 161, '1967-11-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (159, 'HAY Danny', 131, '1963-08-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (160, 'HEM Thon Ponloeu', null, '1979-10-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (161, 'HENKEL Claas', 46, '1972-04-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (162, 'HENNING Andre', 101, '1964-12-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (163, 'HERGEIRSSON Thorir', 160, '1971-09-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (164, 'HERNANDEZ FRAILE Jose Ignacio', 27, '1963-09-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (165, 'HERNANDEZ Sergio', 82, '1970-10-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (166, 'HEYNEN Vital', 74, '1969-12-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (167, 'HIROSE Norikazu', 50, '1963-02-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (168, 'HOAG Glenn', 101, '1976-01-28', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (169, 'HOLANEK Zoltan', 62, '1974-06-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (170, 'HOVASSE Thomas Wayne', 50, '1963-05-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (171, 'HUGHES Daniel', null, '1974-11-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (172, 'HUGHLEY JR Otis', 25, '1961-11-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (173, 'IMURA Masayo', 50, '1974-03-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (174, 'IWABUCHI Kensuke', 50, '1972-04-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (175, 'JACOBSEN Nikolaj', 49, '1977-07-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (176, 'JARDINE Andre', 29, '1973-01-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (177, 'JAUMA CAYUELA Esther', 161, '1973-04-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (178, 'JENNINGS Dee', 32, '1976-03-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (179, 'JEROME Essapa', null, '1975-04-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (180, 'JIA Xiuquan', null, '1972-07-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (181, 'JIMENEZ NIETO Cecilia', 27, '1964-11-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (182, 'JOHNSON Vickie', null, '1977-04-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (183, 'JONES Chris', 101, '1973-09-15', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (184, 'JONES Nathan', 32, '1960-11-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (185, 'KAISER Pierre', 2, '1968-02-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (186, 'KANEKO Makoto', 50, '1970-04-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (187, 'KANG Jae Won', null, '1961-11-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (188, 'KANUNGO Bergin', 395, '1963-08-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (189, 'KAWASE Asaki', 50, '1979-10-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (190, 'KAZAMA Takafumi', 50, '1978-06-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (191, 'KELLER Florian', 46, '1975-10-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (192, 'KERRY Danny', null, '1963-09-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (193, 'KIM Chanbin', null, '1971-04-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (194, 'KIM Hagbum', null, '1977-08-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (195, 'KIRALY Karch', null, '1967-06-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (196, 'KIRKELY Ulrik', 50, '1962-07-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (197, 'KIRKPATRICK Andrew', 32, '1965-06-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (198, 'KITABAYASHI Kenji', 50, '1960-10-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (199, 'KLARENBEEK Auke', 161, '1979-03-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (200, 'KNEZEVIC Nemanja', 205, '1973-09-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (201, 'KOFFI Anthony', null, '1970-10-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (202, 'KONSTANTINOV Aleksei', null, '1974-09-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (203, 'KONTIC Svetlana', 83, '1973-04-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (204, 'KRIKORIAN Adam', null, '1975-09-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (205, 'KRIST JANSSON Aron', 518, '1979-12-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (206, 'KRUMBHOLZ Olivier', 59, '1970-02-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (207, 'KULESZA Katarzyna', 101, '1961-06-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (208, 'KUNTZ Stefan', 46, '1960-04-01', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (209, 'KUZIN Andrey', null, '1974-03-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (210, 'KWIEK Marcos', 404, '1961-04-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (211, 'LAIDLAW Clark', 131, '1972-08-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (212, 'LAMAS Julio', 50, '1974-03-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (213, 'LANG Ping', null, '1971-01-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (214, 'LAVARINI Stefano', null, '1969-07-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (215, 'LAZARO CORRAL Jesus', 27, '1973-05-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (216, 'LETELIER Jose', 117, '1960-02-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (217, 'LOCK Adrian Mayner', 27, '1969-09-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (218, 'LOFTUS Adriana', 220, '1962-04-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (219, 'LOPES BARBOSA Leonard', 403, '1973-07-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (220, 'LOPEZ GUILLEN Melvyn', 404, '1961-08-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (221, 'LOPEZ Monica Susana', 82, '1964-06-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (222, 'LOUCKS Luke', 25, '1970-08-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (223, 'LOZANO Jaime', 220, '1970-12-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (224, 'MACEK Anze', 147, '1974-12-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (225, 'MACKINTOSH Euan Michael Gordon', null, '1976-10-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (226, 'MAEDA Kenzo', 50, '1962-05-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (227, 'MAHLANGU Sibusiso', 319, '1977-09-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (228, 'MAKIRI Hare', 50, '1966-06-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (229, 'MALJKOVIC Marina', 83, '1970-08-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (230, 'MANENTI John', 32, '1979-07-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (231, 'MANZANILLO Andres', 153, '1974-04-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (232, 'MARCZ Tamas', 62, '1964-04-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (233, 'MARIJNE Sjoerd', 366, '1970-03-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (234, 'MARINELLI Fernando', 117, '1964-06-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (235, 'MARTIN LOZANO David', 27, '1975-06-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (236, 'MARTIN Paul', 319, '1961-05-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (237, 'MASHA Mario', 319, '1977-10-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (238, 'MATSUNO Yoshiyuki', 50, '1962-05-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (239, 'MATSUODANI Yasushi', 50, '1963-06-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (240, 'MAYBURY Elena', null, '1966-12-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (241, 'MAYONNADE Emmanuel', 161, '1976-07-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (242, 'MAZZANTI Davide', 77, '1971-01-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (243, 'McCRORIE Christy', 319, '1976-11-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (244, 'McLEOD Shane', 2, '1976-08-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (245, 'MEDINA Bobby', 25, '1967-02-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (246, 'MENDEZ Marcelo Rodolfo', 82, '1970-06-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (247, 'MENGUAL CIVIL Gemma', 27, '1968-08-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (248, 'MENTOOR Delaine', 319, '1968-02-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (249, 'MERCEDES del ROSARIO Jose', 404, '1965-06-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (250, 'MESTDAGH Philip', 2, '1960-09-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (251, 'MEZHENINA Valeriia', 35, '1973-12-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (252, 'MEZIANE Rachid', 59, '1976-08-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (253, 'MIHAILOVIC Predrag', 32, '1966-09-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (254, 'MIREJOVSKY Michal', 28, '1970-02-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (255, 'MIRET GARCIA Daniel', 27, '1966-06-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (256, 'MIURA Keiko', 50, '1964-07-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (257, 'MIYAKAWA Miya', 50, '1972-06-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (258, 'MLADENOVA Albena', 94, '1963-03-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (259, 'MOHAMED Mai', 87, '1961-09-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (260, 'MOHAMED Sayeda', 320, '1974-06-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (261, 'MOHAMMED Silifat', 25, '1974-03-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (262, 'MONDELO GARCIA Lucas', 27, '1963-08-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (263, 'MONTICO Loredana', 32, '1967-06-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (264, 'MONTICO Loredana', 32, '1977-02-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (265, 'MORIYASU Hajime', 50, '1976-12-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (266, 'MOTOMIYA Makihiro', 50, '1968-08-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (267, 'MULATI Adilijiang', null, '1961-10-28', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (268, 'MUNOZ Noe de Jesus', 220, '1973-04-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (269, 'MWAPE Bruce', 395, '1971-02-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (270, 'NAGAE Shoji', 50, '1965-01-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (271, 'NAIDOO Taren', 319, '1963-05-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (272, 'NAKADA Kumi', 50, '1974-11-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (273, 'NAKAGAICHI Yuichi', 50, '1976-10-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (274, 'NCUBE Mthandazo', 319, '1978-08-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (275, 'NEVES Christophe', null, '1961-03-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (276, 'NISHIDA Takumi', 50, '1971-02-23', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (277, 'NOTOANE David', 319, '1969-04-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (278, 'OCA GAIA Miguel Angel', 27, '1973-03-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (279, 'ODAUDU Ogoh', 25, '1970-09-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (280, 'OLOO Felix', 403, '1977-06-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (281, 'OMOTO Yoji', 50, '1976-03-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (282, 'PAGAN CRISTOBAL Angel', null, '1969-12-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (283, 'PALERMI Giovanna', 77, '1975-04-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (284, 'PANTOJA Hernan', 153, '1969-10-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (285, 'PARADELO David', 101, '1967-08-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (286, 'PARRONDO Roberto', 87, '1970-06-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (287, 'PAUL Henry', 101, '1967-09-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (288, 'PECCI Isabella', 519, '1966-10-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (289, 'PEDRERO Ofelia', 220, '1969-04-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (290, 'PEREIRA Paulo Jorge', 56, '1966-04-15', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (291, 'PEREZ Jose', 153, '1979-07-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (292, 'PIBIRI Rossella', 77, '1975-02-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (293, 'PISKAREVA Ekaterina', null, '1978-08-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (294, 'PIZZOLINI Federico', 77, '1963-11-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (295, 'POPOVICH Gregg', null, '1961-08-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (296, 'POROBIC Petar', null, '1976-01-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (297, 'POTTER Anthony', 32, '1978-05-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (298, 'POWELL Katrina', 32, '1972-03-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (299, 'POWELL Neil', 319, '1975-02-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (300, 'PRADO BRANAS Joaquin', 27, '1966-02-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (301, 'PRIESTMAN Bev', 101, '1961-04-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (302, 'RADOI Mirel', 37, '1966-10-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (303, 'RECKINGER Xavier', 46, '1965-10-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (304, 'REID Graham John', 366, '1971-05-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (305, 'REQUENA PERICAS Judit', 27, '1976-06-01', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (306, 'REQUENA PERICAS Judit', 27, '1967-08-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (307, 'RETEGUI Carlos Jose', 82, '1977-10-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (308, 'RETEGUI Carlos Jose', 82, '1973-10-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (309, 'RIBERA ROMANS Jordi', 27, '1977-04-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (310, 'RIISE Hege', null, '1966-06-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (311, 'RILLIE John', 32, '1961-09-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (312, 'RIPOLL Sylvain', 59, '1973-02-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (313, 'RODRIGUEZ Eduardo Rafael', 82, '1969-11-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (314, 'ROEDL Henrik', 46, '1970-11-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (315, 'ROQUES Anthony', null, '1961-10-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (316, 'SACCHETTI Romeo', 77, '1960-02-15', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (317, 'SALAM Mohamed', 87, '1968-09-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (318, 'SAMMELVUO Tuomas', null, '1968-08-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (319, 'SARTI Ronald', 153, '1961-04-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (320, 'SAVIC Dejan', 83, '1964-06-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (321, 'SAVIC Maja', 41, '1962-11-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (322, 'SCARIOLO Sergio', 27, '1977-11-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (323, 'SCHILLING April', 25, '1965-12-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (324, 'SEKULIC Aleksander', 147, '1967-07-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (325, 'SEO Chun Oh', null, '1962-01-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (326, 'SERMANNI Tom', 131, '1980-04-10', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (327, 'SHAHINTAB Mehran', null, '1978-07-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (328, 'SHAHNAZI Shahbaz', 94, '1973-10-01', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (329, 'SHAW Graham', 131, '1972-11-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (330, 'SHAWKY Gharib', 87, '1964-06-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (331, 'SIAM Zaghloul', 87, '1976-08-15', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (332, 'SIGURDSSON Dagur', 50, '1967-01-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (333, 'SIMIYU Innocent', 403, '1964-09-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (334, 'SINGH Shivendra', 366, '1973-01-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (335, 'SMITH Darren', 131, '1972-02-11', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (336, 'SMITH Mark', 101, '1971-04-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (337, 'SOLBERG Glenn', 100, '1968-12-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (338, 'SOYEZ Frederic', 27, '1961-07-13', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (339, 'SPERAW John', null, '1968-08-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (340, 'SPERONI Stefania', null, '1964-10-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (341, 'STALEY Dawn', null, '1970-10-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (342, 'STANIFORTH Dave', 32, '1978-04-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (343, 'STAS Jacques', 2, '1968-06-06', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (344, 'SUNDHAGE Pia Mariane', 29, '1977-04-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (345, 'SVETLICHNAYA Aliona', 42, '1965-08-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (346, 'SZAUDER Gabor', 101, '1974-11-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (347, 'SZAUDER Gabor', 101, '1977-03-01', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (348, 'SZAUDER Nora', 75, '1967-06-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (349, 'TAGLE German', 117, '1964-03-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (350, 'TAKAKURA Asako', 50, '1973-02-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (351, 'TAKITA Risako', 50, '1969-08-02', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (352, 'TARR Heather', null, '1963-06-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (353, 'TARRES CAMPA Ana', 14, '1963-02-25', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (354, 'TARRES CAMPA Ana', 14, '1963-09-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (355, 'TERZIC Zoran', 83, '1964-12-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (356, 'THOMAIDIS Lisa', 101, '1963-04-08', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (357, 'TILLIE Laurent', 59, '1967-11-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (358, 'TOMOMATSU Yumiko', 77, '1977-10-15', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (359, 'TUCAK Ivica', 45, '1970-10-09', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (360, 'TURNER Glenn', 131, '1966-11-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (361, 'UDOKA Ime', null, '1974-10-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (362, 'UDOVICIC Dejan', null, '1977-10-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (363, 'UTKIN Volodymyr', 35, '1975-07-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (364, 'UTSUGI Reika', 50, '1971-05-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (365, 'van GINKEL Robin', 319, '1975-04-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (366, 'van GUNDY Jeff', null, '1976-11-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (367, 'VASQUEZ Diego', 153, '1962-06-20', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (368, 'VEGA HERRERO Anna', 27, '1973-05-14', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (369, 'VILLEGAS Orlando', 153, '1966-11-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (370, 'VITORINO de SOUZA Marcelo', 403, '1978-03-22', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (371, 'VIVER ARZA Carlos Enrique', 27, '1964-05-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (372, 'VLACHOS Theodoros', 14, '1963-09-12', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (373, 'VORONOVA Elena', null, '1974-11-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (374, 'WALL Michael', null, '1967-04-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (375, 'WALSH Tim', 32, '1962-07-26', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (376, 'WANG Jie', null, '1966-04-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (377, 'WANG Jie', null, '1967-02-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (378, 'WANG Yang', null, '1976-07-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (379, 'WEINSTEIN Jerry', null, '1970-11-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (380, 'WIEGMAN Sarina', 161, '1980-08-15', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (381, 'WIRTH Oscar', 117, '1968-11-03', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (382, 'WOELFLIN Roberto Osvaldo', 82, '1978-10-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (383, 'WOICKI Pawel', 74, '1971-04-04', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (384, 'WRIGHT Jerold', null, '1962-10-18', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (385, 'XU Limin', null, '1973-12-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (386, 'YAMAJI Noriko', 50, '1977-02-24', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (387, 'YUAN Lingxi', null, '1973-02-17', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (388, 'YURKIN Sergey', null, '1963-01-27', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (389, 'ZAITSEVA Olesia', 35, '1979-06-19', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (390, 'ZAMORA PEDREIRA Javier', 27, '1967-02-21', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (391, 'ZAMPIERI Francesca', 84, '1965-10-16', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (392, 'ZHANG Xiaohuan', null, '1974-03-05', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (393, 'ZIJP Simon', 161, '1972-10-07', null); 
 INSERT INTO `stat-spot-db`.`Coach` (`coachId`, `name`, `countryId`, `dateOfBirth`, `clubId`) VALUES  (394, 'ZONDI Nkuliso', 319, '1974-04-18', null); 
