<html>
<head>
    <style>
        .icon {
            height: 110px;
            width: 120px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .outset {
            border-style: outset;
            width: 40%;
        }

        body {background-color: whitesmoke;}

        .white {
            background-color: white;
        }

        .blue {
            background-color: #e8f3f8;
        }

        .center {
            margin: auto;
            width: 40%;
            padding: 10px;
        }
    </style>
</head>
<body>
<div class="outset center blue">
    <p>Test</p>
</div>
</body>
</html>
